In [1]:
import sys
sys.version

'3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:09:20) [MSC v.1916 64 bit (AMD64)]'

In [2]:
import cv2
import numpy
import matplotlib
print('OvenCV Version ',cv2.__version__)
print('numpy Version',numpy.__version__)
print('matplotlib Version',matplotlib.__version__)

OvenCV Version  4.6.0
numpy Version 1.25.0
matplotlib Version 3.7.1


# HOW TO SHOW IMAGE

In [3]:
path= r'''C:\Users\singh\open_cv\New folder\photos'''
img_name="licensed-image.jpeg"



img=cv2.imread(path + '\\' + img_name)

img =cv2.resize(img,(600,400))
               
cv2.imshow("image",img)

cv2.waitKey(0)
               
cv2.destroyAllWindows()

In [4]:
import os


In [5]:
img_names=os.listdir(r'C:\Users\singh\open_cv\New folder\photos')
img_names

['download (1).jpeg',
 'download (2).jpeg',
 'download.jpeg',
 'licensed-image.jpeg']

In [6]:
import cv2

path = r'''C:\Users\singh\open_cv\New folder\photos'''

for img_name in img_names:  # Fix variable name in the loop
    img_path_full = path + '\\' + img_name
    img = cv2.imread(img_path_full)
    img = cv2.resize(img, (600, 400))  # You can resize the image here if needed
    if img is None:
        print(f"Error: Image '{img_name}' not found or unsupported format.")
    else:
        cv2.imshow('photo', img)
        cv2.waitKey(1000)  # Display each image for 1 second (adjust the value as needed)

cv2.destroyAllWindows()


In [7]:
import numpy as np


for img_name in img_names:
    img_path_full = path + '\\' + img_name
    img = cv2.imread(img_path_full)
    img = cv2.resize(img, (300, 400))  # You can resize the image here if needed

    img_2=np.hstack((img,img,img))
    img_6=np.vstack((img_2,img_2,img_2))
    
    cv2.imshow('photo',  img_6)
    cv2.waitKey(1000)  # Display each image for 1 second (adjust the value as needed)

cv2.destroyAllWindows()

# HOW TO PLAY VIDEO

In [8]:
# import numpy as np
# import cv2

In [9]:
video_path=r'C:\Users\singh\open_cv\New folder\videos\VID_20230613_153837.mp4'

In [10]:
# to capture video
cap=cv2.VideoCapture(video_path)

while cap.isOpened():
    raju,frame = cap.read()
    if raju:
        frame = cv2.resize(frame,(600, 400))
        cv2.imshow('video_play',frame)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

In [11]:

cap=cv2.VideoCapture(video_path)

while cap.isOpened():
    raju,frame = cap.read()
    if raju:
        frame = cv2.resize(frame,(600, 400))
        
        frame_2=np.hstack((frame,frame))
        frame_4=np.vstack((frame_2,frame_2))
        
        
        cv2.imshow('video_play',frame_4)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

# HOW TO ACCESS CAMERA

In [12]:

cap=cv2.VideoCapture(0)

#IF WE WANT TO ACCESS SECONDARY CAMERA THEN WE HAVE TO GIVE 1 OR ITS NAME

while cap.isOpened():
    raju,frame = cap.read()
    if raju:
        frame = cv2.resize(frame,(600, 400))
        cv2.imshow('video_play',frame)
        
        if cv2.waitKey(25) & 0xff==ord('q'):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

# DIFFERENT THINGS IN DIFFERENT FRAME

In [13]:
import cv2
import numpy as np

path = r'''C:\Users\singh\open_cv\New folder\photos'''
img_name = "licensed-image.jpeg"

cap1 = cv2.VideoCapture(video_path)  # babu's video
cap2 = cv2.VideoCapture(0)  # camera

while cap1.isOpened() and cap2.isOpened():  # Check if both video streams are open
    raju1, frame1 = cap1.read()
    raju2, c_frame = cap2.read()

    if raju1 and raju2:  # Check if frames were successfully read from both streams
        frame1 = cv2.resize(frame1, (600, 400))
        c_frame = cv2.resize(c_frame, (600, 400))

        image = cv2.imread(path + '\\' + img_name)
        image = cv2.resize(image, (600, 400))

        frame_2 = np.hstack((image, c_frame))
        frame_02 = np.hstack((frame1, frame1))  # Use the correct frame variable
        frame_4 = np.vstack((frame_2, frame_02))

        cv2.imshow('video_play', frame_4)

    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

cap1.release()
cap2.release()
cv2.destroyAllWindows()


# READ IMAGE USING OPEN CV

cv2.imread(path,flag)

cv2.imread(path,1) or cv2.imread(path,cv2.IMREAD_COLOR) -- reads the image with RGB

cv2.imread(path,0) or cv2.imread(path,cv2.IMREAD_GRAYSCALE)--reads the image with gray colors

cv2.imread(path,-1) or cv2.imread(path,cv2.IMREAD_UNCHANGED)--it reads the image as is form the source.if the source image is RGB, it loads the image into array with red,green,blue channels.If the source image is ARGB, it loads the image with three colors components along with the alpha or transparency channel


In [14]:
path= r'''C:\Users\singh\open_cv\New folder\photos\licensed-image.jpeg'''

img=cv2.imread(path,cv2.IMREAD_GRAYSCALE)

img =cv2.resize(img,(600,400))

print(img)
               
cv2.imshow("image",img)

cv2.waitKey(0)
               
cv2.destroyAllWindows()

[[119 119 119 ... 139 139 139]
 [119 119 119 ... 141 141 141]
 [121 121 121 ... 141 141 141]
 ...
 [ 53  55  53 ...  64  65  65]
 [ 46  46  43 ...  64  64  64]
 [ 35  38  37 ...  63  63  63]]


# EVERYTHING ABOUT cv2.imshow()

In [15]:
import cv2
import numpy as np

In [16]:
matx=np.zeros((200,200))

In [17]:
matx

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
cv2.imshow('raju',matx)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
img_name = r'''C:\Users\singh\open_cv\New folder\photos\licensed-image.jpeg'''

img=cv2.imread(img_name)

cv2.imshow("image",img)

img = cv2.resize(img, (600, 400))

cv2.waitKey(0)
               
cv2.destroyAllWindows()

# how to save image or numpy array as image

# how to covert video into images

In [20]:
import cv2
import numpy as np
import os

# save numpy array

In [21]:
rand_array=np.random.randint(255,size=(300,600,3))
rand_array

array([[[ 42, 178, 155],
        [ 23, 201,  39],
        [232, 247,  64],
        ...,
        [ 96,  75, 114],
        [251,  36, 219],
        [206,  72, 126]],

       [[122, 178,  44],
        [134,  92,  87],
        [136, 228,  76],
        ...,
        [ 91,   2,   9],
        [ 49,  62,  34],
        [142, 117, 221]],

       [[123, 236, 175],
        [148, 249,  49],
        [ 61, 229, 217],
        ...,
        [ 52,  85, 117],
        [133,  41,  14],
        [247,  90, 235]],

       ...,

       [[205, 238,  95],
        [ 61, 248, 196],
        [243, 109, 186],
        ...,
        [ 52, 210, 150],
        [121,  34, 112],
        [202, 235, 190]],

       [[ 36, 105, 227],
        [  2,  53,  51],
        [110, 138, 219],
        ...,
        [190, 122,  17],
        [ 52,  29, 187],
        [ 12,  70, 205]],

       [[ 95,  77,  70],
        [238, 115, 175],
        [210, 163, 118],
        ...,
        [173,  18, 244],
        [199,  13,  56],
        [154, 148, 151]]

In [22]:
cv2.imwrite('rand_array.png', rand_array)  #imwrite(filename,img[,params])

img=cv2.imread('rand_array.png')
cv2.imshow('image',img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# save image

In [23]:
path= r'''C:\Users\singh\open_cv\New folder\photos\licensed-image.jpeg'''

img=cv2.imread(path)

cv2.imshow("image",img)

cv2.imwrite('licensed-image.png', img) 

img = cv2.resize(img, (600, 400))

cv2.waitKey(0)
               
cv2.destroyAllWindows()

In [24]:
path= r'''C:\Users\singh\open_cv\New folder\photos\licensed-image.jpeg'''

img=cv2.imread(path)

cv2.imshow("image",img)

cv2.imwrite('licensed-image.jpeg', img) 

img = cv2.resize(img, (600, 400))

cv2.waitKey(0)
               
cv2.destroyAllWindows()

# save image from video

In [27]:
video_path=r'C:\Users\singh\open_cv\New folder\videos\VID_20230613_153837.mp4'

os.mkdir('video_to_image')

cap=cv2.VideoCapture(video_path)

img_count = 1

while cap.isOpened():
    raju,frame = cap.read()
    
    if not raju:
        print('unable to read frame')
        break
        
    is_img_write=cv2.imwrite(f'video_to_image\image{img_count}.png',frame)
    
    if is_img_write:
        print(f'video_to_image\image{img_count}.png')
        
        
        cv2.imshow('video_play',frame)
        
        cv2.waitKey(25) & 0xff==ord('q')
        
        img_count+=1
            
            

cap.release()
cv2.destroyAllWindows()

video_to_image\image1.png
video_to_image\image2.png
video_to_image\image3.png
video_to_image\image4.png
video_to_image\image5.png
video_to_image\image6.png
video_to_image\image7.png
video_to_image\image8.png
video_to_image\image9.png
video_to_image\image10.png
video_to_image\image11.png
video_to_image\image12.png
video_to_image\image13.png
video_to_image\image14.png
video_to_image\image15.png
video_to_image\image16.png
video_to_image\image17.png
video_to_image\image18.png
video_to_image\image19.png
video_to_image\image20.png
video_to_image\image21.png
video_to_image\image22.png
video_to_image\image23.png
video_to_image\image24.png
video_to_image\image25.png
video_to_image\image26.png
video_to_image\image27.png
video_to_image\image28.png
video_to_image\image29.png
video_to_image\image30.png
video_to_image\image31.png
video_to_image\image32.png
video_to_image\image33.png
video_to_image\image34.png
video_to_image\image35.png
video_to_image\image36.png
video_to_image\image37.png
video_to_i

video_to_image\image298.png
video_to_image\image299.png
video_to_image\image300.png
video_to_image\image301.png
video_to_image\image302.png
video_to_image\image303.png
video_to_image\image304.png
video_to_image\image305.png
video_to_image\image306.png
video_to_image\image307.png
video_to_image\image308.png
video_to_image\image309.png
video_to_image\image310.png
video_to_image\image311.png
video_to_image\image312.png
video_to_image\image313.png
video_to_image\image314.png
video_to_image\image315.png
video_to_image\image316.png
video_to_image\image317.png
video_to_image\image318.png
video_to_image\image319.png
video_to_image\image320.png
video_to_image\image321.png
video_to_image\image322.png
video_to_image\image323.png
video_to_image\image324.png
video_to_image\image325.png
video_to_image\image326.png
video_to_image\image327.png
video_to_image\image328.png
video_to_image\image329.png
video_to_image\image330.png
video_to_image\image331.png
video_to_image\image332.png
video_to_image\image

KeyboardInterrupt: 